# Generated by Django 5.2.8 on 2025-12-04 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_remove_employee_name_employee_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Unit')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
