# Generated by Django 5.2.8 on 2025-12-04 04:29

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Pack Qty')),
                ('incentive', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('solid', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Selling Price')),
                ('packed_in', models.CharField(blank=True, help_text='e.g. Tin / Bucket / Drum', max_length=50, verbose_name='Packed In')),
                ('min_stock_level', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Min Stock Level')),
                ('raw_material_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Raw Material Cost')),
                ('density', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('company_name', models.CharField(default='DMOR PAINTS', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='master_records', to='masters.product', verbose_name='Select Product')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.unit', verbose_name='Unit')),
            ],
            options={
                'verbose_name': 'Product Master',
                'verbose_name_plural': 'Product Masters',
            },
        ),
    ]
