# Generated by Django 5.2.8 on 2025-12-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_productmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(max_length=200, verbose_name='Term')),
                ('description', models.TextField(verbose_name='Conditions')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Term & Condition',
                'verbose_name_plural': 'Terms & Conditions',
                'ordering': ['id'],
            },
        ),
    ]
