# Generated by Django 5.2.8 on 2025-12-04 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_termcondition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Company')),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('landline_no', models.CharField(blank=True, max_length=20, verbose_name='Landline No')),
                ('manager_name', models.CharField(blank=True, max_length=150, verbose_name='Manager')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email ID')),
                ('proprietor_dob', models.DateField(blank=True, null=True, verbose_name='Proprietor DOB')),
                ('company_size', models.CharField(blank=True, choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], max_length=20, verbose_name='Company Size')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Location')),
                ('gst_no', models.CharField(blank=True, max_length=30, verbose_name='GST No')),
                ('proprietor_name', models.CharField(blank=True, max_length=150, verbose_name='Proprietor Name')),
                ('mobile_no1', models.CharField(blank=True, max_length=20, verbose_name='Mobile No 1')),
                ('mobile_no2', models.CharField(blank=True, max_length=20, verbose_name='Mobile No 2')),
                ('reference_name', models.CharField(blank=True, max_length=150, verbose_name='Refrance Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sales_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='masters.employee', verbose_name='Sales Person')),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
    ]
