# Generated by Django 5.2.8 on 2025-12-04 08:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_percent', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Per %')),
                ('density', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_records', to='masters.product', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product BOM',
                'verbose_name_plural': 'Product BOM Master',
                'unique_together': {('category',)},
            },
        ),
    ]
