# Generated by Django 5.2.9 on 2025-12-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0009_productdevelopment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaster',
            name='inventory_type',
            field=models.CharField(choices=[('FG', 'Finished Goods'), ('PM', 'Packing Material'), ('RM', 'Raw Material')], default='FG', max_length=2),
        ),
        migrations.AlterField(
            model_name='productmaster',
            name='company_name',
            field=models.CharField(blank=True, default='DMOR PAINTS', max_length=255),
        ),
        migrations.AlterField(
            model_name='productmaster',
            name='packed_in',
            field=models.CharField(blank=True, help_text='e.g. Tin / Bucket / Drum', max_length=100, verbose_name='Packed In'),
        ),
    ]
