# Generated by Django 5.2.8 on 2025-12-12 07:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_productmaster_inventory_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sequence', models.IntegerField(default=0)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='masters.productbom')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_items', to='masters.product')),
            ],
            options={
                'ordering': ['sequence', 'id'],
                'unique_together': {('bom', 'product')},
            },
        ),
    ]
