# Generated by Django 5.2.8 on 2025-12-12 07:19

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0011_productbomitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDevelopmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10)),
                ('sequence', models.IntegerField(default=0)),
                ('rate', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('amount', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('solid_percent', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10)),
                ('solid', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('density', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10)),
                ('wt_ltr', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('sv', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('development', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='masters.productdevelopment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='development_items', to='masters.product')),
            ],
            options={
                'ordering': ['sequence', 'id'],
                'unique_together': {('development', 'product')},
            },
        ),
    ]
