# Generated by Django 5.2.8 on 2025-12-02 04:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_order_bill_no_order_on_hold_order_payment_cleared_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mobile1',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number (7–15 digits).', regex='^\\d{7,15}$')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='mobile2',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number (7–15 digits).', regex='^\\d{7,15}$')]),
        ),
    ]
