# Generated by Django 5.2.8 on 2025-12-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_alter_order_mobile1_alter_order_mobile2'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('sales_person', models.CharField(max_length=255)),
                ('order_created', models.DateTimeField()),
                ('delivery_expected_date', models.DateField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('factory_accepted', models.BooleanField(default=False)),
            ],
        ),
    ]
