# Generated by Django 5.2.8 on 2025-12-02 07:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_factoryorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor', models.CharField(max_length=100)),
                ('labour', models.DecimalField(decimal_places=2, help_text='Total labour hours or cost', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.CharField(max_length=100)),
                ('base_qty', models.DecimalField(decimal_places=2, help_text='Base Qty from BOM', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('production_qty', models.DecimalField(decimal_places=2, help_text='Planned production quantity', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('remark', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=150)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operations.batch')),
            ],
        ),
    ]
