# Generated by Django 5.2.8 on 2025-12-02 12:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_dispatch_vehicle_dispatchitem_dispatch_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialInward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inward_date', models.DateField(default=django.utils.timezone.now)),
                ('bill_no', models.CharField(max_length=50)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('master_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.masterproduct')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.supplier')),
            ],
        ),
    ]
