# Generated by Django 5.2.8 on 2025-12-03 02:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_remove_order_created_at_remove_order_payment_remark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialDiscard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('RM', 'Raw Material'), ('FG', 'Finished Goods')], max_length=20)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
