# Generated by Django 5.2.8 on 2025-12-03 02:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_materialdiscard'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('company_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('dispatched_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('returned_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicle', models.CharField(blank=True, max_length=50)),
                ('remark', models.TextField(blank=True)),
                ('returned_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
