# Generated by Django 5.2.8 on 2025-12-03 04:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_materialreturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterproduct',
            name='product_type',
            field=models.CharField(choices=[('FG', 'Finished Goods'), ('RM', 'Raw Material'), ('PK', 'Packing')], db_index=True, default='FG', max_length=2),
        ),
        migrations.AddField(
            model_name='masterproduct',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='masterproduct',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
