# Generated by Django 5.2.9 on 2025-12-13 10:21

import django.db.models.deletion
import operations.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0012_productdevelopmentitem'),
        ('operations', '0012_masterproduct_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='supervisor_emp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_batches', to='masters.employee', verbose_name='Supervisor'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='base_qty',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[operations.models.validate_non_negative]),
        ),
        migrations.AlterField(
            model_name='batch',
            name='labour',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='batch',
            name='production_qty',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[operations.models.validate_non_negative]),
        ),
        migrations.AlterField(
            model_name='batch',
            name='supervisor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='batchitem',
            name='qty',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[operations.models.validate_non_negative]),
        ),
        migrations.AlterField(
            model_name='dispatchitem',
            name='available_qty',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[operations.models.validate_non_negative]),
        ),
        migrations.AlterField(
            model_name='dispatchitem',
            name='qty',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[operations.models.validate_non_negative]),
        ),
        migrations.AlterField(
            model_name='masterproduct',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[operations.models.validate_non_negative]),
        ),
        migrations.AlterField(
            model_name='masterproduct',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[operations.models.validate_non_negative]),
        ),
        migrations.AlterField(
            model_name='order',
            name='available_qty',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, null=True, validators=[operations.models.validate_non_negative]),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, null=True, validators=[operations.models.validate_non_negative]),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, null=True, validators=[operations.models.validate_non_negative]),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, null=True, validators=[operations.models.validate_non_negative]),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, null=True, validators=[operations.models.validate_non_negative]),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, null=True, validators=[operations.models.validate_non_negative]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='capacity_qty',
            field=models.DecimalField(decimal_places=2, help_text='Max load capacity (e.g. in litres or cartons).', max_digits=10, validators=[operations.models.validate_non_negative]),
        ),
    ]
