# Generated by Django 5.2.9 on 2025-12-13 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0012_productdevelopmentitem'),
        ('operations', '0013_batch_supervisor_emp_alter_batch_base_qty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='supervisor_emp',
        ),
        migrations.AlterField(
            model_name='batch',
            name='base_qty',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='batch',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_batches', to='masters.product', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='labour',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='batch',
            name='production_qty',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='batch',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_batches', to='masters.employee', verbose_name='Supervisor'),
        ),
    ]
