# Generated by Django 5.2.9 on 2025-12-14 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0012_productdevelopmentitem'),
        ('operations', '0014_remove_batch_supervisor_emp_alter_batch_base_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batch_items', to='masters.product'),
        ),
    ]
