# Generated by Django 5.2.9 on 2025-12-14 04:39

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0015_alter_batchitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batch_items', to='operations.masterproduct', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='batchitem',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
